[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "vite"
  targetPort = 5173
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
